name: Build & release

on:
  push:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install build dependencies
        run: npm install svgo
      - name: Create dist directory
        run: mkdir dist
      - name: Copy source SVGs
        run: cp -r studios dist/
      - name: Optimize source SVGs
        run: npx svgo --multipass dist/studios/**/*.svg
      - name: ImageMagick Action
        uses: dosaki/ImageMagick-action@patch-1
        with:
          # ImageMagick command to be executed
          command: mogrify -format webp dist/studios/**/*.svg
      - name: Build studios.json
        run: jq -s '.[0]=([.[]]|flatten)|.[0]' studios/**/studio.json > dist/studios.json
      - name: Remove individual JSON files
        run: rm dist/studios/**/studio.json
      - run: touch dist/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
          git-config-name: GitHub Actions
          git-config-email: github-actions[bot]@users.noreply.github.com
